### ISSUE TITLE
Add support for request Context

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_elixir#10]
The Ruby agent has supported a `Context` api, where an application can add small snippets of information to a request, which will be saved and displayed in a trace on the web site.

## For instance:

![admincontroller_index](https://cloud.githubusercontent.com/assets/6119/25545033/571e7388-2c1a-11e7-8c09-3f936181f5bc.png)

We should reimplement this in the Elixir agent as well.

## Hypothetical api:

```
ScoutApm.Context.add(%{
  user: "chris@scoutapp.com",
  subscription: :jumbo,
  messages: 1802
})
```

No nested maps, and the data types would be simple strings, atoms, numbers. (anything else?)

**Comment by karmajunkie** [comment]
Tuples, lists, and maps would be good to have available as well.

**Comment by karmajunkie** [comment]
oh, i see you already addressed the maps question—any particular reason to disallow those? Just to prevent overdoing it on stored request data?

**Comment by itsderek23** [comment]
> oh, i see you already addressed the maps question—any particular reason to disallow those? Just to prevent overdoing it on stored request data?

Good question. Two primary reasons:

1. Currently our UI only supports top-level keys. We don't handle nested context values. 
2. We're working on a new way to query request data, including filtering by context, called [Explorer](https://apm.scoutapp.com/explorer). This won't support nested values initially.

Expanding a tuple into the parent context (ie: prefixing user keys with `user_`) seems like an OK workaround. We aren't ruling out additional types in the future.

**Comment by karmajunkie** [comment]
Ok, good to know, thanks for the update!
