### ISSUE TITLE
 (UndefinedFunctionError) function NaiveDateTime.utc_now/0 is undefined or private

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_apm_elixir#12]
The following exception:

```
[error] GenServer ScoutApm.Store terminating
** (UndefinedFunctionError) function NaiveDateTime.utc_now/0 is undefined or private
    (elixir) NaiveDateTime.utc_now()
    (scout_apm) lib/scout_apm/store.ex:122: ScoutApm.Store.find_or_create_reporting_period/2
```

...occurs as we're calling an Elixir 1.4 function that doesn't exist in Elixir 1.3. We officially support 1.4+, but if it all we need to support 1.3 is returning the current UTC time, there's probably an underlying Erlang function for this.

**Comment by cschneid** [comment]
Elixir has moved onwards, going to close this unless somebody really needs this feature.
