### ISSUE TITLE
(Compilation error) ....priv/static/devtrace/xml_http_script.html: no such file or directory in v0.2.9

### ISSUE THREAD

**Issue by ashutoshrishi** [scoutapp/scout_apm_elixir#17]
After my dependencies upgraded to version `0.2.9` I am getting the following compilation error:

```
** (File.Error) could not read file "/Users/..._umbrella/_build/dev/lib/scout_apm/priv/static/devtrace/xml_http_script.html": no such file or directory
    (elixir) lib/file.ex:244: File.read!/1
    lib/scout_apm/devtrace/plug.ex:7: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

I think the published package is not tracking the file
`priv/static/devtrace/xml_http_script.html` in `mix.exs`.

**Comment by itsderek23** [comment]
@ashutoshrishi - Thx for reporting. 

We've released 0.2.10 which should fix the issue. 

0.2.9 has been retired because of the compile error.

/cc @cschneid

**Comment by rickclare** [comment]
@itsderek23 Compilation now works for us, using v0.2.10

However, when loading our app in the browser, we are getting 404 errors for the scount_instant.js and scout_instant.css assets

<img width="690" alt="scout" src="https://cloud.githubusercontent.com/assets/127204/25863484/ef18a5ce-34e3-11e7-9c3c-54eaaa4aecd0.png">

**Comment by itsderek23** [comment]
@rickclare,

Apologies - try `scout_apm` version 0.2.11. This should fix the missing assets.

**Comment by rickclare** [comment]
@itsderek23 

That's great - v0.2.11 works really well and the new dev-trace functionality is already proving ultra useful in our Phoenix app. Thanks for the fix.

**Comment by itsderek23** [comment]
Great! Ping if you run into any issues.
