### ISSUE TITLE
Silence logging when agent isn't running

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_apm_elixir#25]
We still log messages during the reporting cycle when the log level is `debug` even when monitoring isn't enabled. 

Remove this noise.

**Comment by cschneid** [comment]
The options I laid out in #20 would handle this I think.

**Comment by yogipatel** [comment]
It would be helpful if there was no log output if there's no config. Our dev env doesn't have a Scout config, but the console is full of debug messages from the reporter.

Thanks for Scout+Elixir, it's been so easy to get performance information out of our app.

**Comment by itsderek23** [comment]
@cschneid - we're getting more requests to silence Scout in development.

Mind picking one of the options from #20 - or another simple idea - to address it?

**Comment by yogipatel** [comment]
@itsderek23 I'd be happy to send a PR in the next week or so, if you're open to it.

**Comment by cschneid** [comment]
I just pushed #30 and released it as package version 0.3.1.

It has all logging from the agent go through a pass-through ScoutAPM module, which has 2 different methods of quieting down logs.

* If `monitor: false` is set, turning off the agent, logging will be silent.
* A new setting of `log_level` is added to the configuration, which may be set tighter than your overall application log level. (your app could be at info, while scout is at warn or even error).

**Comment by fbjork** [comment]
I think logging should be disabled if the API key config is omitted

**Comment by cschneid** [comment]
@fbjork opened a new issue to track that (#43), since it's a bit of a different task. Closing this issue, since the logging changes made controlling noise levels much easier.
