### ISSUE TITLE
Ensure agent doesn't log or otherwise break if scout_apm application not started

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_elixir#32]
This came up during a customer's test suite, when they didn't have the `scout_apm` application started.

Make sure that no unnecessary log messages, and no errors are raised in the case of ScoutApm application not being started.

**Comment by cschneid** [comment]
For instance:

```
     ** (exit) exited in: GenServer.call(ScoutApm.Config, {:find, :dev_trace}, 5000)
         ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
     stacktrace:
       (elixir) lib/gen_server.ex:729: GenServer.call/3
       lib/scout_apm/devtrace/plug.ex:11: ScoutApm.DevTrace.Plug.call/2
```

**Comment by mitchellhenke** [comment]
Closing this issue for now as there haven't been any recent reports.  If you do run into this, please let us know!
