### ISSUE TITLE
wrong syntax on docs

### ISSUE THREAD

**Issue by prem-prakash** [scoutapp/scout_apm_elixir#50]
the syntax bellow does not work

```elixir
defmodule Searcher do
  use ScoutApm.Tracing

  # Time associated with this function will appear under "Hound" in timeseries charts.
  # The function will appear as `Hound/open_search` in transaction traces.
  @timing(category: "Hound")
  def open_search(url) do
    navigate_to(url)
  end

  # Time associated with this function will appear under "Hound" in timeseries charts.
  # The function will appear as `Hound/search` in transaction traces.
  @timing(category: "Hound", name: "search")
  def open_search(url) do
    navigate_to(url)
  end
```

tried on a module:

```elixir
defmodule Apollo.Cache.MemcachedAdapter do
  @moduledoc """
  Wrapper around Memcache to allow timing instrumentation
  """
  use ScoutApm.Tracing

  alias Apollo.MemcachedWorker

  @timing category: "Memcached", name: "get"
  def get(key) do
    Memcache.get(MemcachedWorker, key)
  end

  @timing category: "Memcached", name: "set"
  def set(key, value) do
    Memcache.set(MemcachedWorker, key, value)
  end

  @timing category: "Memcached", name: "delete"
  def delete(key) do
    Memcache.delete(MemcachedWorker, key)
  end

  @timing category: "Memcached", name: "incr"
  def incr(key) do
    Memcache.incr(MemcachedWorker, key, default: 1, by: 1)
  end
end
```

the erlang VM starts to consume memory and the module became unresponsive

changing for this syntax it works fine

```elixir
defmodule Apollo.Cache.MemcachedAdapter do
  @moduledoc """
  Wrapper around Memcache to allow timing instrumentation
  """
  import ScoutApm.Tracing

  alias Apollo.MemcachedWorker

  def get(key) do
    timing("Memcached", "get") do
      Memcache.get(MemcachedWorker, key)
    end
  end

  def set(key, value) do
    timing("Memcached", "set") do
      Memcache.set(MemcachedWorker, key, value)
    end
  end

  def delete(key) do
    timing("Memcached", "delete") do
      Memcache.delete(MemcachedWorker, key)
    end
  end

  def incr(key) do
    timing("Memcached", "incr") do
      Memcache.incr(MemcachedWorker, key, default: 1, by: 1)
    end
  end
end

```

**Comment by cschneid** [comment]
Thank you for the report. We've recently reworked some parts of custom instrumentation to play nicer. The function annotations were clever, but caused some issues, and the next release will provide a midpoint option for instrumentation. I'm glad you have the inside-the-function version of tracing working.

To clarify, the code compiled ok, but failed at runtime?

**Comment by prem-prakash** [comment]
yes the code compiled ok but failed at runtime by becoming unresponsive

**Comment by jstr** [comment]
It looks like both the docs linked above and those on Hex.pm (e.g. the code comments) are out of date with regard to the deprecations.

**Comment by cschneid** [comment]
@jstr - I just looked at our [generated docs](https://hexdocs.pm/scout_apm/ScoutApm.Tracing.html) and it looks ok. We do still document the `@transaction` style, which we should further deemphasise, but the newer style `deftransaction` is there as the recommended version.

Can you point to what you're seeing?

**Comment by mitchellhenke** [comment]
The docs have been updated to reflect the deprecation of `@timing` in favor of the new implementation and style.  If it is unclear, please let us know! 🙂
