### ISSUE TITLE
Update HTTPoison Example

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_apm_elixir#53]
Our [help docs](http://help.apm.scoutapp.com/#httpoison) have an example for instrumenting HTTPoison that references [this gist](https://gist.github.com/itsderek23/50296b49df16b266e47cc04d227d4b4a).

@mitchellhenke - can you update that gist (or create a new one, whichever is more appropiate) to handle the comment on the gist:

![image](https://user-images.githubusercontent.com/7880/38520625-8108bcb6-3c00-11e8-9ec7-8f31189ba4d6.png)

...and this one that came through Slack:

![image](https://user-images.githubusercontent.com/7880/38520656-99fc1966-3c00-11e8-84dd-e70594d778a9.png)

/cc @cschneid

**Comment by cschneid** [comment]
We ran into a namespace issue with a customer a while back. If you alias the `ScoutApm.HTTPoison` library, it hides the real HTTPoison name, which makes it impossible to pattern match on the other values in the namespace.
