### ISSUE TITLE
Add option for ignoring requests

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_elixir#75]
The Ruby Agent has several methods for ignoring certain requests, which we should add to the Elixir agent as well.

* Blanket ignore via the `ignore` option. This exists in Elixir already
* Selective ignore by calling a function during a request.

The Selective Ignore feature also allows for user-defined sampling in the case of very high, but relatively uninteresting throughput.

**Comment by cschneid** [comment]
The Ruby impl does some tricks to minimize memory and cpu overhead if it's been informed that the whole transaction will be ignored.

It stops the installed instrumentation from recording new layers at all, wipes any existing ones, and instead switches to only counting call depth, 1, 2, 3, 2, 3, 2, 1, 0 (and at 0, flush the ignored transaction and go on to record the next one like normal)

**Comment by mitchellhenke** [comment]
This was closed in #79
