### ISSUE TITLE
Scout 0.4.14 doesn't work with Ecto 2

### ISSUE THREAD

**Issue by gregnavis** [scoutapp/scout_apm_elixir#87]
Hi!

My set up is as follows:

* Elixir 1.8.2
* Ecto 2.2.8
* Phoenix 1.3.0

I'm getting the following error:

```
     ** (UndefinedFunctionError) function ScoutApm.Instruments.EctoLogger.log/1 is undefined or private
```

It seems that 3c5cf28c9113043ac0d458df867df3095d548ea3 removed `log`.

Downgrading to 0.4.13 solves the problem.

**Comment by cschneid** [comment]
Thank you for the report - sorry about that accidental removal - we'll get it readded and released.
